### PR TITLE
Add Frame wallet

### PR DESCRIPTION
**Pull request by zakimzf**
**USDC/SOL on Solana : mzfc9KQG1kYaCdiojp7Yqt21cJeoYmtwwAtiJ5csCXy
or

*BNB/matic on  evm : 0x7874E8FD57764FfF676F86eE6D95625188250205

Bounty completed as seen on farcaster @mozrt2

### CODE REVIEW

**Comment by mozrt2** [comment]
hi @zakimzf - thanks for contributing. 

Some of the data is inaccurate so I can't merge this yet - frame is only compatible with desktop and also doesn't have an in-app browser for example, I haven't checked the other points. Please make sure to double check the provided info before re-submitting

**Comment by zakimzf** [comment]
@mozrt2 made some necessary changes. Should be able to merge now. Thanks

**Comment by mozrt2** [comment]
Thanks, merged now - the bounty is in USDC, can you confirm the EVM address shared works for a payment on Polygon (can do Optimism or Base alternatively)?

**Comment by zakimzf** [comment]
yes polygon please.

**Comment by mozrt2** [comment]
thanks, bounty sent!

**Pull request merged**
