### PR TITLE
Add Zerion Wallet

### PR DESCRIPTION
**Pull request by abishekdharshan**
Detailed information about Zerion can be found in our Help Center for review: https://help.zerion.io/

For any questions, please reach out to me or inbox@zerion.io!

2 category suggestions from my colleagues:
1. Multichain NFTs support
2. Portfolio tracking (Supporting other wallets): Only Zerion & Rabby support it

### CODE REVIEW

**Comment by mozrt2** [comment]
thanks for the contribution @abishekdharshan - I just did a few quick tests: I wasn't able to resolve any ENS unfortunately (I am on the latest version of the Android app). This is what I get when I try to resolve it:
image

let me know if this is a bug or if there's a mistake in the data

**Comment by mozrt2** [comment]
Hi @abishekdharshan - @iSpeakNerd just submitted a PR to add Zerion with adjusted data (see #17) - I have merged this now so feel free to check it and adjust if you see any inaccurate data there.

**Comment by iSpeakNerd** [comment]
> thanks for the contribution @abishekdharshan - I just did a few quick tests: I wasn't able to resolve any ENS unfortunately (I am on the latest version of the Android app). This is what I get when I try to resolve it: image
> 
> let me know if this is a bug or if there's a mistake in the data

i got L2 ENS to work on browser extension and subdomains to work on browser extension ¯\_(ツ)_/¯

**Comment by mozrt2** [comment]
you're right, it works on browser but not on mobile - thanks for confirming @iSpeakNerd

**Comment by abishekdharshan** [comment]
Happy Monday, @mozrt2!

Thanks for reviewing & publishing Zerion Wallet from my PR. A few feature updates from my team that's worth reviewing:
- Cloud Backup ✅ – we have this in Zerion's Wallet already – across Apple & Android devices
- Scanning (via Blockaid) ✅ – we released tx simulation and transaction scanning with warnings earlier on (both domain & transactions)
- Autoswitch ✅ - we already have this

You can find details here: https://zerion.io/security

Let me know if you have any questions!

**Comment by mozrt2** [comment]
thanks @abishekdharshan just adjusted the points you mentioned, will close the PR now

**Comment by abishekdharshan** [comment]
Thanks for updating this so quickly @mozrt2! 
Our community also pointed out that we have desktop support for our wallet – both via web http://app.zerion.io/ & our macOS native app.

**Comment by iSpeakNerd** [comment]
I didn't include desktop originally bc it was Mac exclusive, haven't tried the browser app version @mozrt2

**Comment by mozrt2** [comment]
thanks for the heads up @abishekdharshan - does it have feature parity with the extension / mobile app or are some features different?

**Comment by abishekdharshan** [comment]
Yes, feature parity with the extension & mobile app – in fact supports connecting other wallets like Metamask, Rainbow, Ledger Nano X, etc with the same features!

— Abi


________
Abi Dharshan 🌐 <https://www.abishekdharshan.com/>

50 California Street Suite 1500 <https://goo.gl/maps/nPdnxCRN41kTtov87>
San Francisco, CA 94111 <https://goo.gl/maps/nPdnxCRN41kTtov87>

telegram: @abishekinguout | talk to me: 🤙 <https://calendly.com/chatwithabishek/20min>

**Pull request closed without merging**
